#!/usr/bin/env python3
# TaichiRTM
# Copyright (C) 2025 Yutaro Hara
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public License
# as published by the Free Software Foundation; either version 2.1
# of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this library. If not, see <https://www.gnu.org/licenses/>.

"""
Example script for TaichiRTM - Step 2: Imaging

This script reads RTM result npz files from 'results/data' directory,
stacks them together, and outputs visualization images to 'results/images'.

Usage:
    python example_2nd_step.py

The script expects npz files generated by example_1st_step.py in results/data/.
"""

import glob
import os
import sys

# Add src directory to path
script_dir = os.path.dirname(os.path.abspath(__file__))
src_dir = os.path.dirname(script_dir)
sys.path.insert(0, src_dir)

import matplotlib.pyplot as plt

from src import compute_display_limits, load_rtm_results, stack_rtm_images


def create_combined_figure(stacked_data: dict, output_path: str, cmap: str = 'gray') -> None:
    """
    Create and save a combined figure with u, v, w components.

    Parameters
    ----------
    stacked_data : dict
        Dictionary containing stacked u, v, w images and extent information
    output_path : str
        Path to save the output image
    cmap : str
        Colormap to use (default: 'gray')
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    extent = stacked_data['extent']

    for ax, comp, label in zip(axes, ['u', 'v', 'w'], ['X', 'Y', 'Z']):
        data = stacked_data[comp]
        vmin, vmax = compute_display_limits(data)
        ax.imshow(data, cmap=cmap, extent=extent, vmin=vmin, vmax=vmax, aspect='auto')
        ax.set_title(f'Reverse Time Migration, {label} axis')
        ax.set_xlabel('x [m]')
        ax.set_ylabel('z [m]')

    plt.tight_layout()
    plt.savefig(output_path, dpi=150)
    plt.close()
    print(f'Combined figure saved to {output_path}')


def create_individual_figures(
    stacked_data: dict,
    output_dir: str,
    name: str,
    cmap: str = 'gray'
) -> None:
    """
    Create and save individual figures for each component.

    Parameters
    ----------
    stacked_data : dict
        Dictionary containing stacked u, v, w images and extent information
    output_dir : str
        Directory to save the output images
    name : str
        Base name for the output files
    cmap : str
        Colormap to use (default: 'gray')
    """
    extent = stacked_data['extent']

    # Use w component's maximum absolute value as the scale reference
    # for consistent color scaling across all individual figures
    _, wmax = compute_display_limits(stacked_data['w'])

    for comp, axis_label in [('u', 'x'), ('v', 'y'), ('w', 'z')]:
        data = stacked_data[comp]
        plt.figure(figsize=(8, 6))
        plt.imshow(data, cmap=cmap, extent=extent, vmin=-wmax, vmax=wmax, aspect='auto')
        plt.title(f'Reverse Time Migration, {axis_label} axis')
        plt.xlabel('x [m]')
        plt.ylabel('z [m]')
        plt.colorbar(label='Amplitude')

        output_path = os.path.join(output_dir, f'{axis_label}_{name}.png')
        plt.savefig(output_path, dpi=150)
        plt.close()
        print(f'Individual figure saved to {output_path}')


def main():
    """Main function to create RTM images from npz results."""
    # Configuration (velocity should match example_1st_step.py)
    velocity = 120
    subtract_mean = True
    cmap = 'gray'

    # Directories (use module-level script_dir)
    data_dir = os.path.join(script_dir, 'results', 'data')
    output_dir = os.path.join(script_dir, 'results', 'images')

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)

    # Find npz files
    npz_files = sorted(glob.glob(os.path.join(data_dir, '*.npz')))

    if not npz_files:
        print(f"No npz files found in {data_dir}")
        print("Please run example_1st_step.py first to generate RTM results.")
        return

    print(f"Found {len(npz_files)} npz files in {data_dir}")

    # Load RTM results
    print("Loading RTM results...")
    results = load_rtm_results(data_dir)

    if not results:
        print("Failed to load RTM results.")
        return

    print(f"Loaded {len(results)} RTM result files")

    # Stack RTM images
    print("Stacking RTM images...")
    stacked_data = stack_rtm_images(results, subtract_mean=subtract_mean)

    # Create combined figure
    combined_path = os.path.join(output_dir, f'{velocity}.png')
    create_combined_figure(stacked_data, combined_path, cmap=cmap)

    # Create individual figures
    create_individual_figures(stacked_data, output_dir, str(velocity), cmap=cmap)

    print(f"\nImaging complete! Images saved to {output_dir}")


if __name__ == '__main__':
    main()
